### ISSUE TITLE
The Allfiles folder has no templates

### ISSUE THREAD

**Issue by mctpjh** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#1]
There are supposed to be several .json templates in the allfiles directory. they are missing and have a file named "test" in each of the days' folders.

**Comment by polichtm** [comment]
resolved

**Comment by KindReality** [comment]
Thank you for getting to this polichtm!

**Comment by polichtm** [comment]
You're welcome
rgds
Marcin
