### ISSUE TITLE
FIle paths look incorrect

### ISSUE THREAD

**Issue by pdlab** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#10]
The file paths in the instructions don't match the repository given.
Example : In the Choose File to Upload dialog box, navigate to the **F:\Labfiles\Mod09\Starter\ folder**

**Comment by polichtm** [comment]
are you OK with replacing the fully qualfied path with the relative path that represents the location of the file in the repo?
rgds
Marcin

**Comment by KindReality** [comment]
May I suggest asking all authors of upcoming classes like these; az-300, az-301, ect...; if there are standards in place for this issue? If there are not, I suggest breaking new ground on that. I feel it will improve quality for there to be a "correct" answer to this issue for all new and upcoming classes. Thank you for considering my position.

**Comment by KindReality** [comment]
As I mentioned in another comment, I observe that standards have been used for a long while related to this issue.

**Comment by polichtm** [comment]
completed
