### ISSUE TITLE
working around azbb error w/ Cloud Bash shell (eg hub and spoke lab )  via an Ubuntu 1804 VM 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#101]
1)	Create an Ubuntu 1804 VM in Azure 
2)	Ssh into the vm: 
         Start Ubuntu bash on your windows 10 (WSL2 ) machine 
         ssh -i <private key>  AzureUser@<pub ip> 
3)	Update apt
          sudo apt-get upgrade   << how to update all software on Ubuntu
4) Check to insure no updates left to process
          sudo -i apt update    << how to check for updates
5 )	Install Azure cli 
                curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                reference https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
6)  install node  
          Install latest version of v10 node.js 
           curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
           sudo apt-get install -y nodejs
7) Verify  the versions 
	node --version
               v10.21.0
         npm  --version
               6.14.4
           Reference:  https://www.fosslinux.com/26264/how-to-install-node-js-and-npm-packages-on-ubuntu.htm
8) Install azbb 
  		npm install -g @mspnp/azure-building-blocks
                     /home/AzureUser/.npm-global/bin/azbb -> /home/AzureUser/.npm-global/lib/node_modules/@mspnp/azure-building-blocks/src/index.js
+ @mspnp/azure-building-blocks@2.2.3
                      updated 1 package in 2.96s

9) exit root 
         exit 
10) cd $HOME
11)  npm config set prefix '~/.npm-global'

12)  Test the azbb command
               azbb 

13) enjoy

**Comment by polichtm** [comment]
Hi Mike
appreciated
rgds
Marcin
