### ISSUE TITLE
AZ-301T02_Lab_Mod02 Obsolete command to create sql db in cosmosdb.

### ISSUE THREAD

**Issue by Bobris** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#102]
az cosmosdb database create --url-connection $URI --key $PRIMARY_KEY --db-name 'FinancialClubDatabase'
This command has been deprecated and will be removed in a future release. Use 'cosmosdb sql database, cosmosdb mongodb database, cosmosdb cassandra keyspace or cosmosdb gremlin database' instead.
This command is implicitly deprecated because command group 'cosmosdb database' is deprecated and will be removed in a future release. Use 'cosmosdb sql database, cosmosdb mongodb database, cosmosdb cassandra keyspace or cosmosdb gremlin database' instead.

**Comment by polichtm** [comment]
Hi Boris, 
we'll consider this once there is a valid, non-preview based replacement. At this, point, you get the following:
Command group 'cosmosdb sql' is in preview. It may be changed/removed in a future release.
rgds
Marcin

**Comment by marksml** [comment]
@polichtm Quick question: The deprecated hint sounds like there is already a confirmed replacement, but the preview hint says there isn't and the command is on preview. This is somehow inconsistent and irritating. Is this the normal sequence of implementations? Which one would be expected in an exam? Thank you, Michael

**Comment by mpolicht** [comment]
Hi Michael,
as per https://docs.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/get-started/removed-deprecated-features-platform-updates 
"A deprecated feature is not in active development and may be removed in a future update."
rgds
Marcin

**Comment by marksml** [comment]
@mpolicht Hi Marcin,
Thank you for your message. Is there a rule about what will be in the exam ( deprecated versus preview)? Thanks, Michael

**Comment by polichtm** [comment]
Hi Michael,
the content of the exam is defined at https://docs.microsoft.com/en-us/learn/certifications/exams/az-301
rgds
Marcin
