### ISSUE TITLE
AZ-301T01_Lab_Mod02 missing "Method: POST"

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#105]
In Excercise 1, Task 4:

Changing the Method to POST is missing

**Comment by polichtm** [comment]
Which specific task are you referring to and what specific change are you suggesting?
rgds
Marcin

**Comment by derhoppe** [comment]
Hi Marcin,

there was a UI change which introduced the "Method" selector in the Code+Test pane. The Method has to be selected as "POST" otherwise you will receive an 404-Not found error in the test console. 

It is in AZ-301T01_Lab_Mod02 Excercise 1, Task 4

rgds,
Sebastian

**Comment by polichtm** [comment]
Hi Sebastian
updated
rgds
Marcin
