### ISSUE TITLE
Errata - AZ-301T04_Lab_Mod02_Building Azure IaaS-Based Server Applications by using ARM.md 

### ISSUE THREAD

**Issue by hawkism** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#107]
Line 450 - 
"In the **Cloud Shell** pane, run the following to create a variable which value designates the name of your Azure subscription:"

It looks like Actual commands to run  should follow this line, but nothing is there and goes on to the next step instead.

Suggested commands could be something like:
az account list --output table
az account set --subscription "XYZSubsriptionname"

**Comment by polichtm** [comment]
updated
