### ISSUE TITLE
AZ-301T04_Lab_Mod03_Deploying Network Infrastructure - deployment fails due to quota

### ISSUE THREAD

**Issue by zensonic** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#112]
Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: westeurope, Current Limit: 10, Current Usage: 9, Additional Required: 2, (Minimum) New Limit Required: 11. Submit a request for Quota increase at

Region: westeurope

**Comment by zensonic** [comment]
student@lab08vm1:~$ grep vmCount ./reference-architectures/hybrid-networking/hub-spoke/hub-spoke.json
                            "vmCount": 1,
                            "vmCount": 1,
                            "vmCount": 1,
                            "vmCount": 1,
                            "vmCount": 1,
                            "vmCount": 1,

student@lab08vm1:~$ grep size ./reference-architectures/hybrid-networking/hub-spoke/hub-spoke.json
                            "size": "Standard_DS1_v2",
                            "size": "Standard_DS1_v2",

thus 10 cores atleast + the jumpbox.

**Comment by polichtm** [comment]
updated to account for the need to increase the quotas
