### ISSUE TITLE
AZ-301T03_Lab_Mod02_Deploying Managed Containerized Workloads to Azure - Jenkins pipeline fails

### ISSUE THREAD

**Issue by www42** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#113]
Exercise 4: Implement DevOps with AKS

Jenkins pipline stage 4 fails due to Kubernetes version 1.16.9

|kubernetesVersion | Jenkins pipeline stage 4 |
|------------------| ------------------------ |
|1.16.9            | failure                  |
|1.16.8            | failure                  |
|1.15.11           | success                  |

**Comment by polichtm** [comment]
updated
rgds
Marcin
