### ISSUE TITLE
AZ-301T02_Lab_Mod03 - VM not showing on Automation account

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#124]
LAB: AZ-301T02_Lab_Mod03
Exercise 2 - Task 3 - step 3

When adding the VM, the VM never shows on the list but when you go to Virtual Machines that VM  exists and has been fully deployed. If I create a VM using the Portal, that new VM shows immediately but the VM crated using the template never shows. 

This is the behavior all my students got. We are using Azure Pass. I redirect then to the "Configuration Deployment" feature on the VM and we were able to do the lab but not following the lab steps.

**Comment by renaudwangler** [comment]
Tip : After waiting a loooooong time the needed VM finally appears ;)

**Comment by tiagocostapt** [comment]
@renaudwangler , yes that was the behaviour...

**Comment by polichtm** [comment]
Hi Tiago and Renaud,
how long is the wait time?
rgds
Marcin

**Comment by tiagocostapt** [comment]
Don't know exactly but more than 30-45 minutes is.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by polichtm** [comment]
Hi Tiago, 
You stated that you used the "Configuration Deployment" feature instead - are you referring to the Configuration management (currently in preview)?
rgds
Marcin

**Comment by tiagocostapt** [comment]
Open your Automation account, then under Configuration Management -> State configuration (DSC), select the "+ Add" option. 
.
![image](https://user-images.githubusercontent.com/11490197/85951206-8f8f9100-b959-11ea-84b8-e676ac5064b9.png)

**Comment by polichtm** [comment]
Hi Tiago and Renaud,
I'm not seeing any delay at all - in which region(s) are you provisioning the VM and the Automation account?
rgds
Marcin

**Comment by renaudwangler** [comment]
> Hi Tiago and Renaud,
> I'm not seeing any delay at all - in which region(s) are you provisioning the VM and the Automation account?
> rgds
> Marcin
Hi !
I think I tried on EastU and a student had a try in westEurope with the same behaviour.
Maybe this was a bug that was solved since...

**Comment by polichtm** [comment]
Hi Renaud, 
appreciate speedy response. 
Yep - this appears to be the case - I tried EastUS...
rgds
Marcin

**Comment by tiagocostapt** [comment]
Same here. West Europe, then moved to East US with same behavior. I can try again and see the result.

**Comment by polichtm** [comment]
Hi Tiago,
appreciate the offer - let us know...
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
