### ISSUE TITLE
Unable to parse parameter: /home/mydirectory/parameters.json

### ISSUE THREAD

**Issue by Manuelvartanian** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#126]
https://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/blob/master/Instructions/AZ-301T03_Lab_Mod02_Deploying%20Managed%20Containerized%20Workloads%20to%20Azure.md

I am trying to accomplish the above lab.
When i reach to Exercise 4 - step 18 
i am getting this error
Unable to parse parameter: /home/mydirectory/parameters.json
![Capture](https://user-images.githubusercontent.com/26378415/86553062-586d4100-bf52-11ea-9049-43d24f437ec2.PNG)

**Comment by JuanQuijano** [comment]
Download both and upload to CloudShell.

**Comment by polichtm** [comment]
Pls use the following syntax
az group deployment create --resource-group $RESOURCE_GROUP --template-uri https://raw.githubusercontent.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/master/allfiles/AZ-301T03/Module_02/LabFiles/Starter/azuredeploy.json --parameters @parameters.json
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
