### ISSUE TITLE
AZ-301T03_Lab_Mod03 - NODE version not available

### ISSUE THREAD

**Issue by massimobonanni** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#127]
In the lab, at Exercise 2, step 5, there is the command:

`az webapp create --name $WEBAPPNAME2 --plan AADesignLab0502-$LOCATION --resource-group $RESOURCE_GROUP_APP --runtime "NODE|14-lts"`

The framework "NODE|14-lts" is not enable.
If you run `az webapp list-runtimes`, you have

[
  "aspnet|V4.7",
  "aspnet|V3.5",
  "DOTNETCORE|2.1",
  "DOTNETCORE|3.1",
  "node|10.0",
  "node|10.6",
  "node|10.14",
  "node|10.15",
  "php|7.2",
  "php|7.3",
  "php|7.4",
  "python|3.6",
  "java|1.7|Tomcat|7.0",
  "java|1.7|Tomcat|8.0",
  "java|1.7|Tomcat|8.5",
  "java|1.7|Tomcat|9.0",
  "java|1.7|Jetty|9.1",
  "java|1.7|Jetty|9.3",
  "java|1.7|Java SE|8",
  "java|1.8|Tomcat|7.0",
  "java|1.8|Tomcat|8.0",
  "java|1.8|Tomcat|8.5",
  "java|1.8|Tomcat|9.0",
  "java|1.8|Jetty|9.1",
  "java|1.8|Jetty|9.3",
  "java|1.8|Java SE|8",
  "java|11|Tomcat|7.0",
  "java|11|Tomcat|8.0",
  "java|11|Tomcat|8.5",
  "java|11|Tomcat|9.0",
  "java|11|Jetty|9.1",
  "java|11|Jetty|9.3",
  "java|11|Java SE|8"
]

while if you run `az webapp list-runtimes --linux`:

[
  "DOTNETCORE|2.1",
  "DOTNETCORE|3.1",
  "NODE|12-lts",
  "NODE|10-lts",
  "NODE|10.1",
  "NODE|10.10",
  "NODE|10.12",
  "NODE|10.14",
  "NODE|10.16",
  "NODE|12.9",
  "JAVA|8-jre8",
  "JAVA|11-java11",
  "TOMCAT|8.5-jre8",
  "TOMCAT|9.0-jre8",
  "TOMCAT|8.5-java11",
  "TOMCAT|9.0-java11",
  "PHP|7.2",
  "PHP|7.3",
  "PYTHON|3.8",
  "PYTHON|3.7",
  "PYTHON|3.6",
  "RUBY|2.5.5",
  "RUBY|2.6.2"
]

In both situations you don't have NODE|14-lts.

**Comment by polichtm** [comment]
updated
