### ISSUE TITLE
AZ301T02_Lab_Mod02 Issue with Powershell script

### ISSUE THREAD

**Issue by N3rdage** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#13]
The setting of Powershell variables are missing leading $ so fail with copy/paste

so for instance 
Line 95: 
    `$RESOURCE_GROUP='AADesignLab0701-RG'`

Line 102:
    `$COSMOSDB_NAME=$(az cosmosdb list --resource-group $RESOURCE_GROUP --query "[0].name" --output tsv)`

Line 107:
    `$PRIMARY_KEY=$(az cosmosdb list-keys --resource-group $RESOURCE_GROUP --name $COSMOSDB_NAME | jq -r '.primaryMasterKey')`

Line 114:
    `$URI="https://$COSMOSDB_NAME.documents.azure.com:443/"`

**Comment by N3rdage** [comment]
have a patch on a branch but no push permissions 😄

**Comment by polichtm** [comment]
This is NOT a PowerShell script. This should be running it from a Bash session of the Cloud Shell

m@Azure:~$ RESOURCE_GROUP='AADesignLab1202-RG'
m@Azure:~$ echo $RESOURCE_GROUP
AADesignLab1202-RG

Btw. you should be able to submit a pull request...

rgds
Marcin

**Comment by N3rdage** [comment]
Apologies Marcin,
Should have read the "click bash" step earlier on and realised it was CLI 😊

**Comment by polichtm** [comment]
np at all - it's easy to miss...
rgds
Marcin
