### ISSUE TITLE
Unable to download deployment content

### ISSUE THREAD

**Issue by edmundlwj** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#137]
In the file https://raw.githubusercontent.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/master/allfiles/AZ-301T03/Module_02/LabFiles/Starter/azuredeploy.json, 

I ran the below command
az deployment group create --resource-group $RESOURCE_GROUP --template-uri https://raw.githubusercontent.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/master/allfiles/AZ-301T03/Module_02/LabFiles/Starter/azuredeploy.json --parameters @parameters.json

Results in the following error message:
{"error":{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://raw.githubusercontent.com/iainfoulds/architecture-center/aks-devops/docs/sample-solutions/app-modernization/templates/devops-with-aks/nested/grafana.json'.

Please help.

**Comment by polichtm** [comment]
Hi Edmund,
this content is no longer maintained. Pls refer to https://github.com/MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design
rgds
Marcin
