### ISSUE TITLE
AZ-301T04 Mod 3 Lab

### ISSUE THREAD

**Issue by mpaione** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#18]
Request students to : 

Task 2: Examine the routing configuration

1. In the **All services** menu, in the **Filter** text box, type **Route tables** and press **Enter**.

1. In the list of results, click **Route tables**.

1. On the **Route tables** blade, click **hub-dmz-rt**.

1. On the **hub-dmz-rt** blade, review the list of routes. Note the **NEXT HOP** entry for the routes **toSpoke1** and **toSpoke2**. 

But **hub-dmz-rt** is not created by json build block.

**Comment by polichtm** [comment]
Can you post the screenshot of what you're seeing on the Route tables blade?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response

**Comment by mpaione** [comment]
No Routes table created.
