### ISSUE TITLE
AZ-301T04 Mod 3 Lab

### ISSUE THREAD

**Issue by mpaione** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#20]
Request students to :
Task 2: Examine the routing configuration
In the All services menu, in the Filter text box, type Route tables and press Enter.
In the list of results, click Route tables.
On the Route tables blade, click hub-dmz-rt.
On the hub-dmz-rt blade, review the list of routes. Note the NEXT HOP entry for the routes toSpoke1 and toSpoke2.
But hub-dmz-rt is not created by json build block.

**No routes created.**

**Comment by polichtm** [comment]
Can you post the screenshot of what you're seeing?
rgds
Marcin

**Comment by mpaione** [comment]
That's will take time due to this lab was done by students last week, so please wait until I reproduce the lab - all resources were removed to avoid out of budget on azure pass account  -.

**Comment by polichtm** [comment]
updated
