### ISSUE TITLE
AZ-301T01-A Module 1 Exercise 2 Task 4 unable to deploy VM from template

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#28]
When attempting to deploy the SUSE vm template using the command 

az group deployment create --resource-group $RESOURCE_GROUP --template-file ~/vm-template.json --parameters @~/vm-template.parameters.json

The following error is received:

Code: **PlatformImageNotFound**
Message: **The platform image 'suse:opensuse-leap:42.3:latest' is not available.  Verify that all fields in the storage profile are correct.**
Target: **imageReference**

Looking over the parameters in the vm-template.json file everything appears to be correct, and checking the availability of that VM set it appears to be available in the selected region.  

No idea why this is failing.

**Comment by polichtm** [comment]
What subscription are you using and which region are you deploying the VM to?
Rgds
Marcin

**Comment by polichtm** [comment]
Pls give it another try
rgds
Marcin

**Comment by XtremeDR** [comment]
I gave it another try, but the error persists.  

I am using an Azure Pass - Sponsorship as my subscription and I have tried deploying the VM in both westus and centralus, both of which should support this VM for deployment if I'm reading the details correctly.
![image](https://user-images.githubusercontent.com/43967240/61048545-f73e7c00-a396-11e9-871c-a970527b9a6d.png)

**Comment by polichtm** [comment]
Can you try deploying the same image (openSUSE-Leap 15-0) from the portal (the same size and the target region)?
rgds
Marcin

**Comment by XtremeDR** [comment]
Deploying the openSUSE-leap 15.0 VM without using the template, using the standard Azure create a resource workflow, outside of cloudshell Bash works without issue.  

Deploying the openSUSE-leap 42.3 VM using the provided template from the Allfiles still fails.

**Comment by polichtm** [comment]
Pls use the updated template from GitHub
Rgds
Marcin

**Comment by XtremeDR** [comment]
The updated template works!  Thanks!

**Comment by polichtm** [comment]
Excellent – you’re welcome…
