### ISSUE TITLE
Could you please let me know where is the online lab link

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#29]
Could you please let me know where is the online lab link for "Online Lab: Deploying Service Instances as Components of Overall Azure Solutions"

Please kindly refer to https://courses.microsoft.com/courses/course-v1:ELMS+AZ-301.1+2019_T2/courseware/3ac69ba7-6c51-b898-e48f-f5b2b8af89ac/d893147ce62c42febbdfa36560d5af4d/1?activate_block_id=block-v1%3AELMS%2BAZ-301.1%2B2019_T2%2Btype%40vertical%2Bblock%40d74d6de26d744188ae70ffafb9e15546

**Comment by bretkean110606** [comment]
+1

Thanks and regards

Bret Kean - Mob: 0771 408 9286

CloudNet Intelligence Consulting Ltd

**Comment by polichtm** [comment]
Pls refer to https://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/blob/master/Instructions/AZ-301T01_Lab_Mod02_Deploying%20Service%20Instances%20as%20Components%20of%20Overall%20Azure%20Solutions.md 
rgds
Marcin
