### ISSUE TITLE
AZ-301T02 Module 2 lab

### ISSUE THREAD

**Issue by nlenzDE** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#3]
Hi guys,

please review the lab described in "AZ-301T02_Lab_Mod02_Deploying Database Instances in Azure.md".

line 122:

>     {
>         "firstName": "Pennington",
>         "lastName": "Oneal",
>         "age": 26,
>         "salary": 90000.00,
>         "company": "Veraq",
>         "isVested": false
>     }

That won't work that way as the primary key "id": "<value>" is missing. Same for line 139.

**Comment by polichtm** [comment]
Addressed the immediate need by designating lastName as the partition key. Unfortunately it looks like the API will need to be modified in order to fix exercise 2. To be continued...
rgds
Marcin

**Comment by djcmct** [comment]
I fudged this by using bash to create the collection without the partition key
URL=’<value of URL from your Cosmos DB>’
KEY=’<value of PRIMARY KEY from your Cosmos DB>’
az cosmosdb database create --url-connection $URI --key $KEY --db-name 'FinancialClubDatabase'
az cosmosdb collection create --url-connection $URI --key $KEY --db-name 'FinancialClubDatabase' --collection-name 'MemberCollection' --throughput 400

Nearly all of he lab works then

**Comment by polichtm** [comment]
seems like a clever workaround.
I'll update the instructions accordingly until we have the API app updated
rgds
Marcin

**Comment by KindReality** [comment]
Polichtm, how did you execute the files are they existed before the course was released? Did you test these files?

**Comment by polichtm** [comment]
Hi Michael,
the issue appears to be related to changes regarding the ability to provision fixed collections via Azure portal. 
rgds
Marcin

**Comment by KindReality** [comment]
Wonderful! Thank you for taking the time to share the information

**Comment by polichtm** [comment]
completed
