### ISSUE TITLE
AZ-301T01 Mod2 lab: Ex. 1, Task 3: can't save github repo settings

### ISSUE THREAD

**Issue by trayhumphrey** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#30]
These steps no longer seem to work. After clicking Continue in step 19 (of the lab, not above), nothing happens. The portal does not switch to the last step to show the Finish button.

We found a workaround by adding the 2 functions from the repo to the function app. You have to be careful to add as anonymous and also change the parameter under Integrate from req to request.

_Originally posted by @trayhumphrey in https://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/issues/8#issuecomment-514570693_

**Comment by polichtm** [comment]
Hi T. Ray,
would you mind elaborating on the workaround that you used?
rgds
Marcin

**Comment by trayhumphrey** [comment]
Hi Marcin,
That fixed it! Thanks so much for the quick response!
Ray

**Comment by polichtm** [comment]
You’re welcome…
