### ISSUE TITLE
AZ-301T03_Lab_Mod03_ Deploying Serverless Workloads to Azure "Linux workers are not available in resource group  ..."

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#34]
Hi,

getting error msg  " Linux workers are not available in resource group AADesignLab0502-RG. Use this link to learn more https://go.microsoft.com/fwlink/?linkid=831180" when trying to create app service plan  **az appservice plan create --is-linux --name "AADesignLab0502-$LOCATION" --resource-group $RESOURCE_GROUP_APP --location $LOCATION --sku B2**

screencap below

David Papkin
MCT
triple_gem@hotmail.com
https://davidpapkin.net

david@Azure:~$
david@Azure:~$ RESOURCE_GROUP_APP='AADesignLab0502-RG'
david@Azure:~$ read -p 'Region: ' LOCATION
Region: southeastasia
david@Azure:~$ az group create --name $RESOURCE_GROUP_APP --location $LOCATION
{
  "id": "/subscriptions/035a7df5-7749-4525-bcd6-9ad6fc3c29ba/resourceGroups/AADesignLab0502-RG",
  "location": "southeastasia",
  "managedBy": null,
  "name": "AADesignLab0502-RG",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": null
}
david@Azure:~$ az appservice plan create --is-linux --name "AADesignLab0502-$LOCATION" --resource-group $RESOURCE_GROUP_APP --location $LOCATION --sku B2
Linux workers are not available in resource group AADesignLab0502-RG. Use this link to learn more https://go.microsoft.com/fwlink/?linkid=831180

![image](https://user-images.githubusercontent.com/24426530/62271833-2dd65680-b46c-11e9-83b0-35a2b541e1f1.png)

**Comment by polichtm** [comment]
Hi David,
could you try eastus instead?
rgds
Marcin

**Comment by dpapkin** [comment]
Hi,

Yes, that worked.

Thank you!!!

David Papkin
http://techresources.info

________________________________

**Comment by polichtm** [comment]
Hi David,
good to see. I updated the instructions to account for this
rgds
Marcin
