### ISSUE TITLE
az-301t01 mod 2 lab typo

### ISSUE THREAD

**Issue by jzpian** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#39]
**Typo in AZ-301 T01 Module 2 Lab**

In Exercise 1 Task 2, the lab references to use the JSON file in the correct path:

\allfiles\AZ-301T01\Module_02\LabFiles\Starter\ 

In Exercise 2 Task 2, the lab references to use the JSON file in the incorrect path:

Existing Path in Lab:

\allfiles\AZ-301T01\Module_01\LabFiles\Starter\logic-app.json

Proposed Fixed Path in Lab:

\allfiles\AZ-301T01\Module_02\LabFiles\Starter\logic-app.json

**Comment by polichtm** [comment]
updated
