### ISSUE TITLE
Error: AZ-301T03/Module_02/LabFiles/Starter/azuredeploy.json 1.13.5 is not supported

### ISSUE THREAD

**Issue by jaysonvelasco** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#41]
During this part of the labs, I encountered an error with AZ-301T03/Module_02/LabFiles/Starter/azuredeploy.json file saying Version 1.13.5 is not supported - This is at Exercise 4, Task 1, item 38.

I noticed changes in the https://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/blob/master/allfiles/AZ-301T03/Module_02/LabFiles/Starter/azuredeploy.json from "kubernetesVersion": "1.13.5" to "kubernetesVersion": "1.14.6".

However, I still ran through some errors. Any ideas?

**Comment by polichtm** [comment]
Hi Jayson
pls give it another try (make sure to follow the updated instructions) and let us know if you are still running into an issue
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
