### ISSUE TITLE
T01 Module 02 incorrect endpoint

### ISSUE THREAD

**Issue by robdy** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#44]
When using default endpoint from Cognitive Services, such as `https://westeurope.api.cognitive.microsoft.com/` in [step 12 here](https://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/blob/master/Instructions/AZ-301T01_Lab_Mod02_Deploying%20Service%20Instances%20as%20Components%20of%20Overall%20Azure%20Solutions.md#task-3-deploy-a-function-app) you'll receive error 500 while testing in [task 4](https://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/blob/master/Instructions/AZ-301T01_Lab_Mod02_Deploying%20Service%20Instances%20as%20Components%20of%20Overall%20Azure%20Solutions.md#task-4-test-a-function-app-using-cognitive-services). You have to add `text/analytics/v2.0` to `EndpointUrl` value in Application Settings:
![2019-09-16 15_20_10-Microsoft Edge](https://user-images.githubusercontent.com/15113729/64961360-9d29cd80-d895-11e9-8153-d6defb62c365.png)

*Credits to Kamil, one of our training participants, not to me*

**Comment by polichtm** [comment]
updated 
rgds
Marcin
