### ISSUE TITLE
AZ-301T02_Lab_Mod02_Deploying Database Instances in Azure - Lab 3 - Task 2 - fails

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#45]
The specified Query returns an error from Azure search - look in attachment

![Capture](https://user-images.githubusercontent.com/39169466/65034113-aaeb5b80-d946-11e9-8bef-386fc7826909.PNG)

**Comment by polichtm** [comment]
updated
rgds
Marcin
