### ISSUE TITLE
Issue with AZ-301.2 Module 2 Online lab EXERCISE 1 Task 3 Step 7 

### ISSUE THREAD

**Issue by yuem99** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#49]
I can't find Documents child node within the MemberCollection node. Please refer to the screen shot attached. 
![labIssue](https://user-images.githubusercontent.com/40189841/65400706-5f431280-dd89-11e9-844c-37c25205d3a7.PNG)

**Comment by polichtm** [comment]
Step 7 states:
Click the Items child node within the MemberCollection node.
Rgds
Marcin
