### ISSUE TITLE
Error in T04 Lab Mod03

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#51]
In Exercise 1 task 3 pt. 2 it states: "In the Open dialog box, navigate to the \allfiles\AZ-301T04\Module_03\LabFiles\Starter\ folder, select the files hub-nva.json, hub-vnet.json, hub-vnet-peering.json, spoke1.json, and spoke2.json and click Open."
Unfortunately you can only upload 1 file at the time, so you need to do this 5 times, 1 for each file. It's a known error in the Cloud Shell but hasn't been fixed yet

**Comment by polichtm** [comment]
updated
