### ISSUE TITLE
Cosmosdb CLI commands are deprecated

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#54]
In AZ-301T02_Lab_Mod02_Deploying Database Instances in Azure.md deprecated 'az cosmosdb'  commands are used. 
e.g. `az cosmosdb database create` and `az cosmosdb collection create`

**Comment by polichtm** [comment]
az cosmosdb database creaete and az cosmosdb collection create are part of the latest Azure CLI version:
https://docs.microsoft.com/en-us/cli/azure/cosmosdb/database?view=azure-cli-latest#az-cosmosdb-database-create
https://docs.microsoft.com/en-us/cli/azure/cosmosdb/collection?view=azure-cli-latest#az-cosmosdb-collection-create
rgds
Marcin

**Comment by andrePKI** [comment]
Allright, but in cloudshell I assume to be using up to date CLI, hence I was surprised to see the "deprecated" warnings

**Comment by prabhushrikant** [comment]
I have suddently started seeing `deprecated` error for `az cosmosdb database create` and `az cosmosdb collections create` command. What's the correct solution?

**Comment by polichtm** [comment]
For the time being, pls use az cosmosdb commands. To be continued...
rgds
Marcin
