### ISSUE TITLE
Timing on day 4

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#56]
When using the recommended amount of time for the four chapters in AZ-301T04 the accumulated amount of time used is 8 hours. When we add 2 hours for breaks we have a ten hour day. This is not working for most participants.

**Comment by polichtm** [comment]
What content would you suggest to be removed?
rgds
Marcin

**Comment by polichtm** [comment]
to be considered in future course updates
