### ISSUE TITLE
T03 Lab Module 2 - missing directory change

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#59]
In Exercise 3 Task 1 the user changes to directory ˜/azure-voting-app-redis. In Task 2 the user is still in this directory so the command git clone https://github.com/kubernetes-incubator/metrics-server.git clones to directory ˜/azure-voting-app-redis/metrics-server/. 

Please add "cd .." before executing the clone, otherwise the command in Task 2, step 2: kubectl create -f ~/metrics-server/deploy/1.8+/ doesn't work.

rgds, sebastian

**Comment by polichtm** [comment]
Hi Sebastian
completed
rgds
Marcin
