### ISSUE TITLE
az-301t04 Mod 2 Lab

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#6]
Instructions in Exercise 1 to use the portal to create the vm are based on the old style blades, not the newer tabby pages, i know that we can expect recent updates to Azure to mean that the lab instructions are different, but this update is quite old.

If you replace all of Exercise 1 task 2 with

1.	In the upper left corner of the Azure portal, click Create a resource.
2.	At the top of the New blade, in the Search the Marketplace text box, type Windows Server 2016 and press Enter.
3.	On the Everything blade, in the search results, click Windows Server 2016 Datacenter.
4.	On the Windows Server 2016 Datacenter blade, click the Create button.
5.	On the Basics tab, perform the following tasks:
	Leave the Subscription drop-down list entry set to its default value.
	In the Resource group section, select the Create new option and, in the text box, type AADesignLab0301-RG.
	In the Name text box, enter the value lab03vm0.
	In the Region drop-down list, select an Azure region to which you want to deploy resources in this lab.
	Leave the Availability options drop down list set to its default value.
	Leave the Image drop down at the default.
	On the Size, click the entry representing the size DS1_v2 and click the Select button.
	In the Username text box, enter the value Student.
	In the Password and Confirm password text boxes, enter the value Pa55w.rd1234.
	Public Inbound Ports select Allow selected ports and then select HTTP from the drop down
	Leave the Already have a Windows license? option set to its default value
	Click the Next:Disks button.

6.	On the Disks tab, leave all defaults and click Next:Networking
7.	On the Networking Tab perform the following
	Click Virtual network, on the Create virtual network blade, specify the following settings and click OK:
	In the Name text box, enter the value lab03vnet0.
	In the Address space text box, enter the value 10.3.0.0/16.
	In the Subnet name text box, enter the value subnet-0.
	In the Subnet address range text box, enter the value 10.3.0.0/24, click OK.
	Leave the Public IP address entry set to its default value.
	Click Review + Create.
8.	On the Review + Create tab, review the settings of your new virtual machine and click the Create button.
9.	Do not wait for the deployment to complete and proceed to the next task.

And all of exercise 1 task 7 with

1.	In the hub menu in the Azure portal, click Resource groups.
2.	On the Resource groups blade, click the entry representing the resource group into which you deployed the virtual machine.
3.	On the resource group blade, click the entry representing the virtual machine you deployed.
4.	On the Virtual machine blade, locate the Public IP address entry, and identify its value.
5.	Open a new Microsoft Edge tab and navigate to the IP address you identified in the previous step.
6.	Verify that you are able to access the default Internet Information Services webpage.
7.	Close the new browser tab.

This then matches the current interface

**Comment by polichtm** [comment]
resolved

**Comment by KindReality** [comment]
How does this happen? Obviously these steps have not been tested in any way as this aspect of the interface changed months before the course launched. .
