### ISSUE TITLE
UI inconsistency in T03 Lab Mod03

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#65]
In T03 Mod03 Excercise 3, Task 1, step 10 students are required to select value "Basic" from a drop down field which is in this case a text field in the UI. Option 1: change the corresponding template to display a drop down, Option 2: change "Basic" to "B1" and enter B1 in the text field.

rgds, Sebastian

**Comment by polichtm** [comment]
Hi Sebastian
updated
rgds
Marcin
