### ISSUE TITLE
Offer for SLES image is now out of date for AZ-301T01 Module 01 exercise 1

### ISSUE THREAD

**Issue by arron-f** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#68]
https://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign/blame/master/allfiles/AZ-301T01/Module_01/LabFiles/Starter/vm-template.json

The 'offer' and 'sku' values in the above file don't match current offerings, in the AZ-301T01 Module 01

**Comment by polichtm** [comment]
updated
