### ISSUE TITLE
[clarification]

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#70]
Hi
I don't understand the meaning of the "Before we start" part of these labs since the students are told to have a look at many tools they won't use in the labs … is this a remain of an old version of the labs I did not use ?
Would be nice to remove this part since it could be confusing for some students.

**Comment by polichtm** [comment]
Hi Renaud, 
valid point - this will be removed...
rgds
Marcin

**Comment by polichtm** [comment]
To be addressed in the next revision of the labs
