### ISSUE TITLE
Missing instruction files for AZ-301T02_Lab_Mod01_Backing Azure Solutions with Azure Storage

### ISSUE THREAD

**Issue by kristapsozols** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#72]
Hi,
where is missing instructions for  AZ-301T02_Lab_Mod01 storage Accounts. In slides there is reference to them, but nothint here in github

**Comment by polichtm** [comment]
This will be accounted for in the updated version of the lab
rgds
Marcin

**Comment by kristapsozols** [comment]
But I need to provide this course before that, then I can use 20535 LAB?

**Comment by polichtm** [comment]
Unfortunately this course is no longer supported/maintained. Have you considered using a demo instead?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
