### ISSUE TITLE
missing step on AZ-301T02_Lab_Mod02_Deploying Database Instances in Azure.md

### ISSUE THREAD

**Issue by manojsundaram** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#75]
AZ-301T02_Lab_Mod02_Deploying Database Instances in Azure.md, Exercise 2, step 16

It should include a point about collecting a document ID and using it on swagger. This is a missing steps

**Comment by polichtm** [comment]
Hi Manoj
Would you mind clarifying what specifically you mean by this?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
