### ISSUE TITLE
missing step on AZ-301T03_Lab_Mod02_Deploying Managed Containerized Workloads to Azure.md

### ISSUE THREAD

**Issue by manojsundaram** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#76]
These steps are missing.
AZ-301T03_Lab_Mod02_Deploying Managed Containerized Workloads to Azure.md -> exercise 4 -> step 17

after this step is run, user will be asked to provide the Kubernetes version. Have to run "az aks get-versions --location <MY-LOCATION>" and then choose a version from there.

Some of the latest versions did not work for me and had to resort to 1.14.8 for it to work

**Comment by polichtm** [comment]
updated
