### ISSUE TITLE
AZ-301T01_Lab_Mod02: Error testing Function App

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#78]
AZ-301T01_Lab_Mod02_Deploying Service Instances as Components of Overall Azure Solutions.md

Ex 1 Task 4 Step 4: Click the Run button produces error:  "Cannot perform runtime binding on a null reference". Cannot proceed.

![Screenshot (5012)](https://user-images.githubusercontent.com/22414394/77849759-facf9880-719b-11ea-8a46-1a2132025c9b.png)

**Comment by polichtm** [comment]
Investigating
rgds
Marcin

**Comment by polichtm** [comment]
updated
rgds
Marcin
