### ISSUE TITLE
DetermineKeyPhrases doesn't work

### ISSUE THREAD

**Issue by bibliothek** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#79]
`2020-04-14T12:36:19.297 [Error] Executed 'Functions.DetermineKeyPhrases' (Failed, Id=62f19b01-713a-4b2d-bb53-b17eb8959dd1) Cannot perform runtime binding on a null reference`

Tried it with the latest changes, but I believe the URL for the HttpClient is now not set correctly.

According to the lab, you should append "/text/analytics/v2.1/languages" to the cognitive services URL, but that URL then doesn't work when you try to call keyPhrases

Probably the Azure Functions should just get the endpoint and construct the route in the code.

**Comment by polichtm** [comment]
Hi Martin
this has been resolved
rgds
Marcin
