### ISSUE TITLE
az-301t01 Mod 2 lab

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#8]
Portal has updated, Deployment Options is now Deployment Center.

Exercise 1 Task 3 replace steps 16 thru 21 with

16.	In the Platform features tab, click the Deployment Center link in the Code Deployment section.
17.	 On the Deployments Center select External and click continue.
18.	 Select App Service Kudu build server and click continue.
19.	In the Repository text box, type https://github.com/azure-labs/cognitive-services-function
20.	In the Branch box type master.
21.	In the Repository Type section, ensure that the Git option is selected, click continue and then Finish.
22.	 Wait for the deployment to complete before you proceed to the next task.

**Comment by polichtm** [comment]
completed

**Comment by trayhumphrey** [comment]
These steps no longer seem to work. After clicking Continue in step 19 (of the lab, not above), nothing happens. The portal does not switch to the last step to show the Finish button.

We found a workaround by adding the 2 functions from the repo to the function app. You have to be careful to add as anonymous and also change the parameter under Integrate from req to request.
