### ISSUE TITLE
AZ-301T01_Lab_Mod01_Securing Secrets in Azure.md: VMSize error

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#80]
Ex 2   Task 4 Step 1: Error at deployment: "The requested size for resource…is   currently not available in location…". (When using the Azure Pass). 
--
Solution: 
Use  CloudShell Editor (braces {} icon) to update vm-template.json by changing vmSize property value to   "Standard_D2s_v3" and save changes,   close the CloudShell Editor then resubmit deployment at command prompt. 

![Screenshot (5052)](https://user-images.githubusercontent.com/22414394/79687039-7ad4a580-8212-11ea-8054-0e050e131021.png)

**Comment by polichtm** [comment]
updated
