### ISSUE TITLE
AZ-301T01_Lab_Mod01_Securing Secrets in Azure.md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#81]
AZ-301T01_Lab_Mod01_Securing Secrets in Azure.md: Minor UI changes:

Ex 1   Task 2 Step 5: No need to click Select for Pricing Tier. i.e. "Click   Pricing tier, on the Pricing tier blade, click Standard, and then click   Select" should be "Under Pricing tier, verify Standard is   selected".
Ex 1   Task 2 Step 5: "Click the Create button" should be "Click the Review+Create button then click the Create button"
Ex 1   Task 4 Step 3: Ignore "select the Use existing option, and then,"
Ex 1   Task 6 Step 9: Ignore "select the Use existing option, and then,"
Ex 1   Task 6 Step 19: Ignore "select the Use existing option, and then,"
Ex 2   Task 5 Step 7: Note that cursor will not move when entering password at command prompt.

**Comment by polichtm** [comment]
updated
