### ISSUE TITLE
AZ-301T01_Lab_Mod02_Deploying Service Instances...md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#82]
AZ-301T01_Lab_Mod02_Deploying Service Instances...md: Minor UI changes:
--
Ex 1   Task 3 Step 17: If prompted, select Continue.
Ex 1   Task 3 Step 19: Scroll all the way to the bottom (use both scroll bars on the right) to see External under DropBox. You may have to scroll right first in   order to scroll down.
Ex 1   Task 4 Step 3: May have to scroll right to see Test tab.
Ex 1   Task 4 Step 4: May have to scroll left to see Run button.
Ex 1   Task 4 Step 4: May have to scroll down and right to see Output section. If error, make sure your Application Settings were updated correctly.
Ex 2   Task 1 Step 5: Ignore "select the Use existing option, and then,"
Ex 2   Task 1 Step 5: "Click the Create button" should be "Click the Review+Create button then click the Create button"

**Comment by polichtm** [comment]
updated
