### ISSUE TITLE
AZ-301T02_Lab_Mod02_Deploying Database Instances in Azure.md: Minor UI Changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#83]
AZ-301T02_Lab_Mod02_Deploying Database Instances in Azure.md: Minor UI Changes:
--

Ex 1   Task 2 Step 5: "Click the Create button" should be "Click the   Review+Create button then click the Create button"
Ex 1   Task 2 Step 6: "5 minutes" should be "10-15 minutes".
Ex 1   Task 3 Step 2: May have to select the SQL API Refresh icon first to display the FinancialClubDatabase.
Ex 1   Task 3 Step 5: The query should show zero items.
Ex 1   Task 3 Step 10: The Save button may be under the ellipsis menu.
Ex 2   Task 1 Step 11: Ignore "select the Use existing option, and then,"
Ex 2   Task 2 Step 5: If prompted, select Continue after Save.
Ex 2   Task 2 Step 10: GET Response Body should show 2 items.
Ex 2   Task 2 Step 14: POST Response Body should show 50 items added.
Ex 2   Task 2 Step 17: GET Response Body should show 52 items now.
Ex 3   Task 1 Step 5: Ignore "select the Use existing option, and then,"
Ex 3   Task 2 Step 4: "click Import data and then click Next: Connect to your   data." should be just "click Import data."
Ex 3   Task 2 Step 5: "Click the Next: Add cognitive search (optional) "   should be "Click the Next: Add cognitive skills (optional) "
Ex 3   Task 2 Step 7: "On the Index blade" should be "On the Customize target index blade"
Ex 3   Task 3 Step 5:  If prompted, select   Continue after Save.
Ex 3   Task 3 Step 13: GET Response Body should show 2 items.
Ex 3   Task 3 Step 16: GET Response Body should show 1 item.

**Comment by polichtm** [comment]
updated
