### ISSUE TITLE
AZ-301T02_Lab_Mod03_Deploying...md: VMSize error

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#84]
AZ-301T02_Lab_Mod03_Deploying...md: VMSize error:
--
Ex 1   Task 3 Step 7: Error at deployment: "The requested size for resource…is   currently not available in location…". (When using the Azure Pass). Use   CloudShell Editor (braces {} icon)  to   update vm-template.json by changing vmSize property value to "Standard_D2s_v3" and save changes, close the CloudShell Editor then resubmit   deployment at command prompt.

![Screenshot (5055)](https://user-images.githubusercontent.com/22414394/79699268-65846900-825c-11ea-980d-1dda5add1735.png)

**Comment by polichtm** [comment]
updated
