### ISSUE TITLE
AZ-301T02_Lab_Mod03_Deploying...md: Minor UI issues

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#85]
AZ-301T02_Lab_Mod03_Deploying...md: Minor UI issues:
--
Ex 1   Task 3 Step 1: skip this step, unnecessary.
Ex 2   Task 3 Step 9: May have to select the Refresh option first to see the new Node.
Ex 2   Task 3 Step 13: May have to wait for 30 minutes for Status to change from Pending to Compliant.

**Comment by polichtm** [comment]
updated
