### ISSUE TITLE
AZ-301T03_Lab_Mod02_Deploying Managed...md: Ex 1: VMSize change required for Azure Pass

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#86]
AZ-301T03_Lab_Mod02_Deploying Managed...md: VMSize change required for Azure Pass:
--
Ex 1   Task 3 Step 4: "--node-vm-size Standard_DS1_v2" should be   "--node-vm-size Standard_D2s_v3"

![Screenshot (5056)](https://user-images.githubusercontent.com/22414394/79707488-a7c49f00-828a-11ea-975c-1ebd47d5c504.png)

**Comment by polichtm** [comment]
updated
