### ISSUE TITLE
AZ-301T03_Lab_Mod02_Deploying Managed...md: Ex 4: VMSize error for Azure Pass

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#87]
AZ-301T03_Lab_Mod02_Deploying Managed...md: Ex 4: VMSize error for Azure Pass
--

Ex 4   Task 1 Step 18: Error at deployment: "The requested size for resource…is  currently not available in location…". (When using the Azure Pass). Cannot continue.

![Screenshot (5059)](https://user-images.githubusercontent.com/22414394/79712692-92a33c80-8299-11ea-8689-7ef3db55cc25.png)

**Comment by polichtm** [comment]
updated
