### ISSUE TITLE
AZ-301T03_Lab_Mod02_Deploying Managed...md: Ex 3: Metrics-server GitHub error

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#88]
AZ-301T03_Lab_Mod02_Deploying Managed...md: Ex 3: Metrics-server GitHub error
--

Ex 3   Task 2 Step 2: Error: "the path   "/home/.../metrics-server/deploy/kubernetes/" does not exist. From   GitHub: "WARNING: You should no longer use manifests from master branch   (previously available in deploy/kubernetes directory). They are now meant   solely for development.". GitHub updates made 4/22/20. Cannot continue.

![Screenshot (15)](https://user-images.githubusercontent.com/22414394/80045134-86ef8a00-84d4-11ea-8188-186c53974474.png)

**Comment by polichtm** [comment]
updated
