### ISSUE TITLE
AZ-301T04_Lab_Mod02_Building Azure IaaS...md: VMSize errors with Azure Pass

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#89]
AZ-301T04_Lab_Mod02_Building Azure IaaS...md: VMSize errors with Azure Pass:
--
Ex 1   Task 2 Step 5: "Ensure that the size is set to Standard   DS1 v2" should be "Ensure that the size   is set to Standard D2s v3"
Ex 2   Task 1 Step 4: change Size   property value under vm variable to "Standard_D2s_v3" and save file.
Ex 3   Task 3 Step 10: Error at deployment: "The requested size for resource…is   currently not available in location…". (When using the Azure Pass). Use   CloudShell Editor (braces {} icon)  to   update /reference-architectures/virtual-machines/single-vm/parameters/windows/single-vm.json   by changing Size property value to   "Standard_D2s_v3" and save changes,   close the CloudShell Editor then resubmit deployment at command prompt.
Ex 3   Task 5 Step 1: Use CloudShell Editor (braces {} icon)  to update /reference-architectures/virtual-machines/single-vm/parameters/linux/single-vm.json   by changing Size property value to   "Standard_D2s_v3" and save changes,   close the CloudShell Editor then resubmit deployment at command prompt.

**Comment by polichtm** [comment]
updated
