### ISSUE TITLE
AZ-301_T03_Exercise1_Task3_Step4

### ISSUE THREAD

**Issue by mrsmjparker** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#9]
BEFORE YOU BEGIN THIS LAB......
KNOW that every region does not support every VM size.

As of 2/21/2019 - if you don't want to spend all day trying different sizes, be sure to use:
REGION: westeurope
VM Size: Standard_DS2_V2

**Comment by polichtm** [comment]
That's documented at https://azure.microsoft.com/en-us/global-infrastructure/services/
Unfortunately there is no guarantee that the size available in a given region today will be available in the same region at a later date
rgds
Marcin

**Comment by mrsmjparker** [comment]
I do realize that.  This is why I put a date on the issue, in case someone wants to try that.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by polichtm** [comment]
appreciated
rgds
Marcin

**Comment by molenaar** [comment]
You also have https://azure.microsoft.com/en-us/regions/offers/ to see which regions are available for an Azure pass. It is always save to start with a default option like the ds1 or ds2 V2. Afterwards you can scale up if needed.

**Comment by djcmct** [comment]
If you want to identify which vm sizes are available to your subscription then try

Get-AzComputeResourceSku | where {$_.Locations -icontains "westeurope"} | Where-Object {($_.ResourceType -ilike "virtualMachines")}

Replace westeurope with your preferred region

**Comment by polichtm** [comment]
I gather you meant to include the underscore ($_)
Get-AzComputeResourceSku | where {$_.Locations -icontains "eastus2"} | Where-Object {($_.ResourceType -ilike "virtualMachines")}.
Unfortunately, I don't believe this works. As far as I can tell, you will get the listing of all VM sizes available at a given location, regardless of whether you can actually deploy them or not
rgds
Marcin

**Comment by djcmct** [comment]
If you copy and paste, the _'s are there

It lists under Restrictions the availability to your subscription

![git2](https://user-images.githubusercontent.com/47788394/53242835-ddc5bd80-369d-11e9-8905-2bde7cd8891b.PNG)

**Comment by polichtm** [comment]
Yep - that's that pesky md... ;)
Unfortunately, I don't believe this information is reliable. Here is an excerpt of the sample output from the Azure Sponsorship (which, according to https://azure.microsoft.com/en-us/regions/offers/ is not available in eastus2) - when run against eastus2:

![image](https://user-images.githubusercontent.com/10284906/53243674-a859a980-3676-11e9-8c93-c6bb6f6b4de3.png)

rgds
Marcin

**Comment by djcmct** [comment]
Fair enough, although I'm not sure that https://azure.microsoft.com/en-us/regions/offers/ is up to date,
I've had delegates creating VM's in North Europe & UK South this week using the Azure pass allocated to the course, neither regions are listed :)

**Comment by polichtm** [comment]
It appears that you are correct ;)
I just successfully deployed a Standard F1_s VM in eastus2 in an Azure Sponsorship subscription...
In other words, your suggestion seems perfectly valid 
rgds
Marcin

**Comment by polichtm** [comment]
updated lab instructions
