### ISSUE TITLE
AZ-301T04_Lab_Mod02_Building Azure IaaS...md: Minor UI changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#90]
AZ-301T04_Lab_Mod02_Building Azure IaaS...md: Minor UI changes:
--
Ex 1   Task 2 Step 6: Choose Standard HDD for OS Disk type.
Ex 1   Task 2 Step 8: Ignore Enable backup option.
Ex 1   Task 4 Step 5: Ignore "select the Use existing option, and then,"
Ex 1   Task 5 Step 6: "and click OK" should be "and click   Create".
Ex 1   Task 6 Step 9: Ignore "select the Use existing option, and then,"

**Comment by polichtm** [comment]
updated
