### ISSUE TITLE
AZ-301T04_Lab_Mod03_Deploying Network...md: VMSize errors for Azure Pass

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#91]
AZ-301T04_Lab_Mod03_Deploying Network...md: VMSize errors for Azure Pass:
--
Ex 1   Task 5 Step 5: Error at deployment: "sku is unavailable in   location…". (When using the Azure Pass). Use CloudShell Editor (braces   {} icon)  to update hub-vnet.json   by adding the following after the vmcount property setting (line 33): 
"size": Standard_D2s_v3",                                                                                                               
and save changes, close the CloudShell   Editor then resubmit deployment at command prompt.
Ex 1   Task 6 Step 9: Error at deployment: "sku is unavailable in   location…". (When using the Azure Pass). Use CloudShell Editor (braces   {} icon)  to update spoke1.json   by adding the following after the vmcount property setting (line 45):              
"size": "Standard_D2s_v3",                                                                                                               
and save changes, close the CloudShell   Editor then resubmit deployment at command prompt.
Ex 1   Task 6 Step 19: Error at deployment: "sku is unavailable in   location…". (When using the Azure Pass). Use CloudShell Editor (braces   {} icon)  to update spoke2.json   by adding the following after the vmcount property setting (line 45):               
"size": "Standard_D2s_v3",                                                                                                               
and save changes, close the CloudShell   Editor then resubmit deployment at command prompt.
Ex 1   Task 8 Step 9: Error at deployment: "sku is unavailable in   location…". (When using the Azure Pass). Use CloudShell Editor (braces   {} icon)  to update hub-nva.json   by adding the following after the vmcount property setting (line 11):               
"size": "Standard_D2s_v3",                                                                                                               
and save changes, close the CloudShell   Editor then resubmit deployment at command prompt.

**Comment by polichtm** [comment]
updated
