### ISSUE TITLE
AZ-301T04_Lab_Mod04_Deploying Messaging...md: Minor UI Changes

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#92]
AZ-301T04_Lab_Mod04_Deploying Messaging...md: Minor UI Changes:
--
Ex 2   Task 1 Step 5: "In the Secure transfer required section, ensure that the   Disabled option is selected." should be "Under Advanced, in the   Secure transfer required section, ensure that the Disabled option is   selected."
Ex 2   Task 1 Step 5: "Leave the Configure virtual networks option set to its   default value." should be "Leave the Networking tab option set to   its default value."
Ex 2   Task 1 Step 5: "Click the Create button" should be "Click the   Review+Create button then click the Create button"
Ex 2   Task 1 Step 10: "click the Blobs tile." should be "click the   Containers tile."
Ex 2   Task 1 Step 12: "Click the OK button." should be "Click the   Create button."
Ex 2   Task 2 Step 4: "Click the Create button" should be "Click the   Review+Create button then click the Create button"
Ex 2   Task 2 Step 8: Close Cloudshell first.
Ex 2   Task 4 Step 11: "click the Blobs tile." should be "click the   Containers tile."
Ex 2   Task 4 Step 13: Click the Blob file and select Edit to see the contents   "Hello World"

**Comment by polichtm** [comment]
updated
