### ISSUE TITLE
AZ-301T03_Lab_Mod03_Deploying Serverless Workloads to Azure.md has wrong resource group in cloud shell setup

### ISSUE THREAD

**Issue by yuuzhan** [MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign#98]
AADesignLab0901-RG is what is written, should be AADesignLab0501-RG for it to be cleaned up in the cleanup phase of the lab.

**Comment by polichtm** [comment]
updated
rgds
Marcin
